@echo off
echo Fixing SWC warnings...
node fix-all-swc.js
echo.
echo Reinstalling dependencies...
call npm install
echo.
echo Cleaning cache...
call npm run clean
echo.
echo Starting development server...
call npm run dev 