@echo off
echo Dang chuan bi moi truong phat trien...
echo Xoa file trace neu co...
powershell -Command "Remove-Item -Path .next\\trace -Force -ErrorAction SilentlyContinue"

echo Tao cac file static can thiet...
node generate-static-files.js

echo Dang khoi dong server...
npm run dev
