@echo off
echo Dang chuan bi moi truong phat trien...
echo Xoa file trace neu co...
powershell -Command "Remove-Item -Path .next\trace -Force -ErrorAction SilentlyContinue"
echo Dang khoi dong server...
npm run dev
