@echo off
echo === Start development server ===
echo Ẩn cảnh báo Next.js...
node hide-warnings.js
echo Sửa lỗi file trace...
node fix-trace-error.js
echo Running development server...
call npm run dev:silent 