'use client';

import { createContext, useState, useContext, useEffect, ReactNode } from 'react';

type Language = 'vi' | 'en';

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, any>) => string;
};

interface LanguageProviderProps {
  children: ReactNode;
}

// Tạo một context mới
const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translations
const translations: Record<Language, Record<string, string>> = {
  vi: {
    // Admin Notifications
    'admin.notifications.title': 'Quản lý thông báo',
    'admin.notifications.list': 'Danh sách thông báo',
    'admin.notifications.edit': 'Chỉnh sửa',
    'admin.notifications.settings': 'Cài đặt',
    'admin.notifications.create': 'Tạo thông báo mới',
    'admin.notifications.noNotifications': 'Chưa có thông báo nào',
    'admin.notifications.noNotificationsDesc': 'Tạo thông báo đầu tiên để gửi tới người dùng',
    'admin.notifications.type.promotion': 'Khuyến mãi',
    'admin.notifications.type.update': 'Cập nhật',
    'admin.notifications.type.order': 'Đơn hàng',
    'admin.notifications.type.system': 'Hệ thống',
    'admin.notifications.priority.high': 'Cao',
    'admin.notifications.priority.medium': 'Trung bình',
    'admin.notifications.priority.low': 'Thấp',
    'admin.notifications.created': 'Tạo',
    'admin.notifications.readCount': 'Đã đọc',
    'admin.notifications.sentTo': 'Gửi tới',
    'admin.notifications.expires': 'Hết hạn',
    'admin.notifications.viewDetails': 'Xem chi tiết',
    'admin.notifications.editBtn': 'Chỉnh sửa',
    'admin.notifications.deleteBtn': 'Xóa',
    'admin.notifications.cancelBtn': 'Hủy',
    'admin.notifications.createBtn': 'Tạo thông báo',
    'admin.notifications.updatingBtn': 'Đang cập nhật...',
    'admin.notifications.updateBtn': 'Cập nhật thông báo',
    'admin.notifications.creatingBtn': 'Đang tạo...',
    'admin.notifications.form.title': 'Tiêu đề thông báo *',
    'admin.notifications.form.titlePlaceholder': 'Nhập tiêu đề thông báo',
    'admin.notifications.form.content': 'Nội dung thông báo *',
    'admin.notifications.form.contentPlaceholder': 'Nhập nội dung thông báo',
    'admin.notifications.form.type': 'Loại thông báo *',
    'admin.notifications.settings.title': 'Cài đặt thông báo',
    'admin.notifications.settings.automatic': 'Thông báo tự động',
    'admin.notifications.settings.autoOrder': 'Thông báo đơn hàng tự động',
    'admin.notifications.settings.autoPromotion': 'Thông báo khuyến mãi tự động',
    'admin.notifications.settings.autoUpdate': 'Thông báo cập nhật tự động',
    'admin.notifications.settings.email': 'Thông báo qua email',
    'admin.notifications.settings.retention': 'Số ngày lưu trữ thông báo',
    'admin.notifications.settings.retentionDesc': 'Thông báo sẽ tự động bị xóa sau số ngày này',
    'admin.notifications.settings.saveBtn': 'Lưu cài đặt',
    'admin.notifications.success': 'Thông báo đã được tạo thành công!',
    'admin.notifications.updateSuccess': 'Thông báo đã được cập nhật thành công!',
    'admin.notifications.deleteSuccess': 'Thông báo đã được xóa thành công!',
    'admin.notifications.settingsSaved': 'Cài đặt thông báo đã được lưu!',
    'admin.notifications.error': 'Đã xảy ra lỗi khi tạo thông báo',
    'admin.notifications.updateError': 'Đã xảy ra lỗi khi cập nhật thông báo',
    'admin.notifications.deleteError': 'Đã xảy ra lỗi khi xóa thông báo',
    'admin.notifications.connectionError': 'Đã xảy ra lỗi khi kết nối đến máy chủ',
    'admin.notifications.people': 'người',
    
    // Terms page
    'terms.title': 'Điều khoản dịch vụ',
    'terms.lastUpdated': 'Cập nhật lần cuối',
    'terms.section1.title': 'Giới thiệu',
    'terms.section1.content': 'Chào mừng bạn đến với {siteName}! Các Điều khoản Dịch vụ này ("Điều khoản") chi phối việc truy cập và sử dụng trang web, sản phẩm và dịch vụ của chúng tôi. Bằng cách truy cập hoặc sử dụng dịch vụ của chúng tôi, bạn đồng ý tuân theo các Điều khoản này.',
    'terms.section2.title': 'Tài khoản của bạn',
    'terms.section2.content': 'Để sử dụng một số tính năng của dịch vụ chúng tôi, bạn cần tạo tài khoản. Bạn chịu trách nhiệm duy trì tính bảo mật của tài khoản và mật khẩu của mình, đồng thời bạn cũng chịu trách nhiệm cho tất cả hoạt động diễn ra dưới tài khoản của mình.',
    'terms.section3.title': 'Nội dung và quyền sở hữu trí tuệ',
    'terms.section3.content': '{companyName} và bên cấp phép sở hữu tất cả các quyền, quyền sở hữu và lợi ích đối với dịch vụ, bao gồm tất cả quyền sở hữu trí tuệ liên quan. Bạn không được sao chép, sửa đổi, phân phối, hoặc bán bất kỳ phần nào của dịch vụ của chúng tôi mà không có sự cho phép rõ ràng bằng văn bản.',
    'terms.section4.title': 'Giấy phép sử dụng',
    'terms.section4.content': '{companyName} cấp cho bạn giấy phép sử dụng cá nhân, không độc quyền, không thể chuyển nhượng để sử dụng dịch vụ của chúng tôi. Bạn không được sao chép, sửa đổi, phân phối, bán, cho thuê, thuê, hoặc cấp phép phụ bất kỳ phần nào của dịch vụ.',
    'terms.section5.title': 'Giá cả và thanh toán',
    'terms.section5.content': 'Đối với các dịch vụ trả phí, bạn đồng ý thanh toán tất cả các khoản phí liên quan. Chúng tôi có thể thay đổi giá cả bằng cách thông báo trước cho bạn. Việc thanh toán không được hoàn lại trừ khi có quy định khác trong chính sách hoàn tiền của chúng tôi.',
    'terms.section6.title': 'Bảo mật và dữ liệu cá nhân',
    'terms.section6.content': 'Chúng tôi thu thập và xử lý dữ liệu cá nhân của bạn theo',
    'terms.section6.privacyPolicy': 'Chính sách Bảo mật',
    'terms.section6.content2': 'của chúng tôi. Bằng cách sử dụng dịch vụ của chúng tôi, bạn đồng ý với việc thu thập và xử lý dữ liệu theo chính sách này.',
    'terms.section7.title': 'Tuyên bố từ chối trách nhiệm',
    'terms.section7.content': 'Dịch vụ của chúng tôi được cung cấp "nguyên trạng" và "như sẵn có". {companyName} từ chối tất cả các bảo đảm, dù rõ ràng hay ngụ ý, bao gồm nhưng không giới hạn ở các bảo đảm về tính thương mại, sự phù hợp cho một mục đích cụ thể, và không vi phạm.',
    'terms.section8.title': 'Giới hạn trách nhiệm',
    'terms.section8.content': 'Trong mọi trường hợp, {companyName} sẽ không chịu trách nhiệm đối với bất kỳ thiệt hại gián tiếp, ngẫu nhiên, đặc biệt, hậu quả hoặc trừng phạt nào, bao gồm mất lợi nhuận, doanh thu, dữ liệu, hoặc cơ hội kinh doanh.',
    'terms.section9.title': 'Chấm dứt',
    'terms.section9.content': 'Chúng tôi có thể đình chỉ hoặc chấm dứt quyền truy cập của bạn vào tất cả hoặc một phần của dịch vụ nếu bạn vi phạm các Điều khoản này, hoặc nếu chúng tôi tin rằng việc sử dụng của bạn có thể gây thiệt hại cho {companyName} hoặc người dùng khác.',
    'terms.section10.title': 'Thay đổi điều khoản',
    'terms.section10.content': 'Chúng tôi có thể sửa đổi các Điều khoản này bất kỳ lúc nào. Nếu chúng tôi thực hiện những thay đổi quan trọng, chúng tôi sẽ thông báo cho bạn. Việc tiếp tục sử dụng dịch vụ của chúng tôi sau khi thay đổi có hiệu lực đồng nghĩa với việc bạn chấp nhận các điều khoản mới.',
    'terms.section11.title': 'Luật áp dụng',
    'terms.section11.content': 'Các Điều khoản này sẽ được điều chỉnh và giải thích theo luật pháp Việt Nam, không liên quan đến xung đột các nguyên tắc pháp luật.',
    'terms.section12.title': 'Liên hệ',
    'terms.section12.content': 'Nếu bạn có bất kỳ câu hỏi nào về các Điều khoản này, vui lòng liên hệ với chúng tôi qua địa chỉ email:',
    'terms.section12.content2': 'hoặc truy cập trang',
    'terms.section12.contactPage': 'Liên hệ',
    'terms.section12.content3': 'của chúng tôi.',

    // Header
    'nav.home': 'Trang chủ',
    'nav.products': 'Sản phẩm',
    'nav.about': 'Giới thiệu',
    'nav.contact': 'Liên hệ',
    'nav.warranty': 'Bảo hành',
    'nav.login': 'Đăng nhập',
    'nav.logout': 'Đăng xuất',
    'nav.account': 'Tài khoản',
    'nav.admin': 'Quản trị',
    'auth.signOut': 'Đăng xuất',
    'auth.signIn': 'Đăng nhập',
    
    // Login page
    'login.welcome': 'Chào mừng trở lại!',
    'login.continue': 'Để tiếp tục sử dụng các dịch vụ của XLab',
    'login.connect': 'Kết nối an toàn với tài khoản Google của bạn',
    'login.google': 'Tiếp tục với Google',
    'login.secure': 'Bảo mật 100%',
    'login.terms': 'Bằng cách tiếp tục, bạn đồng ý với',
    'login.termsLink': 'Điều khoản dịch vụ',
    'login.and': 'và',
    'login.privacyLink': 'Chính sách bảo mật',
    'login.ourCompany': 'của chúng tôi.',
    
    // Homepage
    'home.slogan': 'Tối ưu hiệu quả, tối thiểu chi phí!',
    'home.search': 'Tìm kiếm phần mềm, ứng dụng...',
    'home.loadMore': 'Xem thêm',
    'home.aboutTitle': 'Về XLab',
    'home.aboutDesc1': 'XLab là nền tảng cung cấp các giải pháp phần mềm tích hợp AI tiên tiến giúp người dùng nâng cao hiệu suất công việc và cuộc sống hàng ngày.',
    'home.aboutDesc2': 'Sứ mệnh của chúng tôi là đem đến cho người Việt cơ hội tiếp cận với các công cụ phục vụ làm việc, học tập, giải trí với giá cả phải chăng và chất lượng quốc tế.',
    'home.learnMore': 'Tìm hiểu thêm',
    'home.domesticProduct': 'Sản phẩm trong nước',
    'home.vietnamDevs': 'Phát triển bởi đội ngũ kỹ sư Việt Nam',
    'home.support247': 'Hỗ trợ 24/7',
    'home.supportTeam': 'Đội ngũ hỗ trợ tận tâm',
    'home.highSecurity': 'Bảo mật cao',
    'home.encryptedData': 'Dữ liệu được mã hóa an toàn',
    'home.reasonablePrice': 'Giá cả hợp lý',
    'home.budgetOptions': 'Nhiều lựa chọn phù hợp mọi ngân sách',
    'home.aiIntegration': 'Tích hợp AI',
    'home.aiSupport': 'Công nghệ AI tiên tiến hỗ trợ bạn',
    'home.continuousUpdates': 'Cập nhật liên tục',
    'home.newFeatures': 'Luôn được cập nhật tính năng mới',
    'home.achievements': 'Thành tựu của chúng tôi',
    'home.customers': 'Khách hàng tin dùng',
    'home.softwareSolutions': 'Giải pháp phần mềm',
    'home.yearsExperience': 'Năm kinh nghiệm',
    'home.software': 'Phần mềm',
    'home.services': 'Dịch vụ',
    'home.featuredProducts': 'Sản phẩm nổi bật',
    'home.newProducts': 'Sản phẩm mới',
    'home.viewAll': 'Xem tất cả',
    'home.noSoftware': 'Chưa có phần mềm',
    'home.updateSoon': 'Chúng tôi sẽ sớm cập nhật các phần mềm.',
    'home.noServices': 'Chưa có dịch vụ',
    'home.updateServices': 'Chúng tôi sẽ sớm cập nhật các dịch vụ.',
    'home.faq': 'Câu hỏi thường gặp',
    'home.faqDesc': 'Giải đáp những thắc mắc phổ biến của khách hàng về sản phẩm và dịch vụ của XLab',
    'home.faq1Title': 'Làm thế nào để tải xuống phần mềm?',
    'home.faq1Desc': 'Bạn có thể tải xuống phần mềm miễn phí tại trang sản phẩm tương ứng sau khi đăng nhập vào tài khoản của mình. Đối với sản phẩm trả phí, bạn cần hoàn tất thanh toán trước khi tải xuống.',
    'home.faq2Title': 'Làm thế nào để kích hoạt bản quyền?',
    'home.faq2Desc': 'Sau khi mua sản phẩm, bạn sẽ nhận được mã kích hoạt qua email. Mở ứng dụng, vào phần "Kích hoạt bản quyền" và nhập mã này để sử dụng đầy đủ tính năng.',
    'home.faq3Title': 'Tôi có thể sử dụng trên bao nhiêu thiết bị?',
    'home.faq3Desc': 'Mỗi bản quyền cho phép bạn sử dụng trên tối đa 3 thiết bị khác nhau. Nếu bạn muốn sử dụng trên nhiều thiết bị hơn, vui lòng mua thêm bản quyền hoặc nâng cấp lên gói doanh nghiệp.',
    'home.faq4Title': 'Chính sách hoàn tiền như thế nào?',
    'home.faq4Desc': 'Chúng tôi có chính sách hoàn tiền trong vòng 7 ngày kể từ ngày mua nếu sản phẩm không đáp ứng nhu cầu của bạn. Vui lòng liên hệ với đội ngũ hỗ trợ để được hướng dẫn.',
    'home.faq5Title': 'Làm thế nào để liên hệ hỗ trợ kỹ thuật?',
    'home.faq5Desc': 'Bạn có thể liên hệ đội ngũ hỗ trợ kỹ thuật qua email support@xlab.vn, hotline 1900.xxxx hoặc chat trực tiếp trên website. Chúng tôi phản hồi trong vòng 24 giờ làm việc.',
    'home.faq6Title': 'XLab có cung cấp giải pháp cho doanh nghiệp không?',
    'home.faq6Desc': 'Có, chúng tôi có các gói dịch vụ đặc biệt dành cho doanh nghiệp với ưu đãi về giá và hỗ trợ kỹ thuật chuyên biệt. Vui lòng liên hệ với chúng tôi để có giải pháp phù hợp nhất.',
    'home.moreQuestions': 'Xem thêm câu hỏi',
    'home.ctaTitle': 'Sẵn sàng nâng cao hiệu suất công việc với XLab?',
    'home.ctaDesc': 'Chúng tôi cung cấp nhiều mức giá ưu đãi đặc biệt dành cho khách hàng mua số lượng lớn. Càng mua nhiều, mức giảm giá càng cao. Chúng tôi cam kết mang đến cho bạn những giải pháp tốt nhất với chi phí hợp lý nhất.',
    'home.contactUs': 'Liên hệ tư vấn',
    
    // Product card
    'product.addToCart': 'Thêm vào giỏ',
    'product.buyNow': 'Mua ngay',
    'product.added': 'Đã thêm',
    'product.week': 'tuần',
    'product.purchasesPerWeek': '{count}/tuần',
    
    // About page
    'about.title': 'Giới thiệu về XLab',
    'about.subtitle': 'Đồng hành cùng doanh nghiệp của bạn trong hành trình chuyển đổi số',
    'about.values': 'Giá trị cốt lõi của chúng tôi',
    'about.innovation': 'Đổi mới',
    'about.innovationDesc': 'Không ngừng sáng tạo và đổi mới công nghệ để mang lại giá trị tốt nhất',
    'about.quality': 'Chất lượng',
    'about.qualityDesc': 'Cam kết chất lượng cao nhất trong mọi sản phẩm và dịch vụ',
    'about.integrity': 'Chính trực',
    'about.integrityDesc': 'Luôn giữ vững đạo đức kinh doanh và minh bạch trong mọi hoạt động',
    'about.collaboration': 'Hợp tác',
    'about.collaborationDesc': 'Xây dựng mối quan hệ đối tác lâu dài dựa trên sự tôn trọng và hợp tác cùng có lợi',
    'about.partnership': 'Hợp tác cùng XLab',
    'about.partnershipDesc': 'Chúng tôi luôn sẵn sàng lắng nghe và đồng hành cùng doanh nghiệp của bạn trong hành trình chuyển đổi số và phát triển bền vững.',
    'about.contactNow': 'Liên hệ ngay',
    'about.exploreServices': 'Khám phá dịch vụ',

    // About page - Additional keys
    'about.pageTitle': 'Về chúng tôi',
    'about.pageSubtitle': 'XLab - Đơn vị tiên phong trong lĩnh vực phát triển phần mềm và các giải pháp công nghệ tại Việt Nam',
    'about.ourStory': 'Câu chuyện của chúng tôi',
    'about.storyP1': 'XLab được thành lập vào năm 2018 bởi một nhóm kỹ sư phần mềm đam mê và có tầm nhìn về việc tạo ra các giải pháp công nghệ tiên tiến, giúp doanh nghiệp Việt Nam nâng cao hiệu quả hoạt động và năng lực cạnh tranh trong kỷ nguyên số.',
    'about.storyP2': 'Sau hơn 10 năm hoạt động và phát triển, XLab đã trở thành đối tác công nghệ tin cậy của hàng trăm doanh nghiệp trong và ngoài nước, từ các công ty khởi nghiệp cho đến các tập đoàn lớn thuộc nhiều lĩnh vực khác nhau như tài chính, bán lẻ, sản xuất, giáo dục và y tế.',
    'about.storyP3': 'Chúng tôi tự hào về đội ngũ nhân sự tài năng và đam mê công nghệ, với hơn 100 chuyên gia phần mềm, kỹ sư hệ thống, và chuyên gia tư vấn giàu kinh nghiệm, luôn tận tâm với mục tiêu mang lại những giải pháp tối ưu cho đối tác và khách hàng.',
    'about.mission': 'Sứ mệnh',
    'about.missionDesc': 'Sứ mệnh của XLab là ứng dụng công nghệ tiên tiến để tạo ra các giải pháp phần mềm xuất sắc, giúp doanh nghiệp Việt Nam tối ưu hóa quy trình, tăng năng suất và phát triển bền vững trong kỷ nguyên số. Chúng tôi cam kết mang đến những sản phẩm và dịch vụ chất lượng cao, đáp ứng nhu cầu đa dạng của khách hàng, đồng thời góp phần thúc đẩy sự phát triển của ngành công nghệ thông tin Việt Nam.',
    'about.vision': 'Tầm nhìn',
    'about.visionDesc': 'XLab hướng tới trở thành doanh nghiệp công nghệ hàng đầu tại Việt Nam và khu vực Đông Nam Á trong lĩnh vực phát triển phần mềm và cung cấp giải pháp công nghệ thông tin toàn diện. Chúng tôi nỗ lực trở thành đối tác tin cậy và lâu dài của các doanh nghiệp trong hành trình chuyển đổi số, đồng thời là môi trường làm việc lý tưởng cho các tài năng công nghệ phát triển sự nghiệp.',
    'about.coreValues': 'Giá trị cốt lõi',
    'about.coreValuesDesc': 'Những giá trị tạo nên văn hóa và định hướng mọi hoạt động của XLab',
    'about.value1': 'Chất lượng',
    'about.value1Desc': 'Đặt chất lượng sản phẩm và dịch vụ lên hàng đầu, không ngừng cải tiến để đạt được sự xuất sắc',
    'about.value2': 'Đổi mới',
    'about.value2Desc': 'Khuyến khích tư duy sáng tạo, dám thử nghiệm những ý tưởng mới và công nghệ tiên tiến',
    'about.value3': 'Hợp tác',
    'about.value3Desc': 'Xây dựng mối quan hệ đối tác lâu dài dựa trên sự tôn trọng và hợp tác cùng có lợi',
    'about.value4': 'Trách nhiệm',
    'about.value4Desc': 'Làm việc với tinh thần trách nhiệm cao, cam kết hoàn thành mọi cam kết với khách hàng',
    
    // Contact page
    'contact.title': 'Liên hệ với chúng tôi',
    'contact.subtitle': 'Hãy liên hệ với chúng tôi để được tư vấn về giải pháp phù hợp nhất cho doanh nghiệp của bạn.',
    'contact.pageTitle': 'Liên hệ với chúng tôi',
    'contact.pageSubtitle': 'Hãy liên hệ với chúng tôi để được tư vấn về giải pháp phù hợp nhất cho doanh nghiệp của bạn.',
    'contact.sendMessage': 'Gửi tin nhắn cho chúng tôi',
    'contact.yourName': 'Họ và tên của bạn',
    'contact.yourEmail': 'Email của bạn',
    'contact.yourPhone': 'Số điện thoại',
    'contact.yourCompany': 'Công ty',
    'contact.serviceInterest': 'Dịch vụ bạn quan tâm',
    'contact.selectService': '-- Chọn dịch vụ --',
    'contact.softwareDev': 'Phát triển phần mềm',
    'contact.cloudServices': 'Dịch vụ đám mây',
    'contact.consulting': 'Tư vấn công nghệ',
    'contact.techSupport': 'Hỗ trợ kỹ thuật',
    'contact.other': 'Khác',
    'contact.message': 'Tin nhắn',
    'contact.send': 'Gửi tin nhắn',
    'contact.sending': 'Đang gửi...',
    'contact.info': 'Thông tin liên hệ',
    'contact.address': 'Địa chỉ',
    'contact.email': 'Email',
    'contact.phone': 'Điện thoại',
    'contact.connectWithUs': 'Kết nối với chúng tôi',
    'contact.required': 'Trường bắt buộc',
    'contact.successMessage': 'Cảm ơn bạn đã liên hệ! Chúng tôi sẽ phản hồi trong thời gian sớm nhất.',
    'contact.errorMessage': 'Có lỗi xảy ra khi gửi form. Vui lòng thử lại sau.',
    'contact.callUs': 'Gọi chúng tôi',
    'contact.emailUs': 'Email chúng tôi',
    'contact.visitUs': 'Tới thăm chúng tôi',
    'contact.workingHours': 'Giờ làm việc',
    'contact.faq': 'Câu hỏi thường gặp',
    'contact.faqSubtitle': 'Tìm câu trả lời nhanh cho các câu hỏi thường gặp',
    'contact.followUs': 'Theo dõi chúng tôi trên mạng xã hội',
    'contact.newsletterTitle': 'Đăng ký nhận bản tin của chúng tôi',
    'contact.newsletterSubtitle': 'Nhận thông tin mới nhất và cập nhật',
    'contact.newsletterPlaceholder': 'Nhập email của bạn',
    'contact.newsletterSubmit': 'Đăng ký',
    'contact.monday': 'Thứ hai',
    'contact.tuesday': 'Thứ ba',
    'contact.wednesday': 'Thứ tư',
    'contact.thursday': 'Thứ năm',
    'contact.friday': 'Thứ sáu',
    'contact.saturday': 'Thứ bảy',
    'contact.sunday': 'Chủ nhật',
    'contact.closed': 'Đóng cửa',

    // Common buttons
    'button.getStarted': 'Get Started',
    'button.learnMore': 'Learn More',
    'button.viewDetails': 'View Details',
    'button.addToCart': 'Add to Cart',
    'button.buyNow': 'Buy Now',
    'button.download': 'Download',
    'button.contactUs': 'Contact Us',
    'button.viewAll': 'View All',

    // Voucher widget
    'voucher.title': 'Mã giảm giá',
    'voucher.viewAll': 'Xem tất cả',
    'voucher.loading': 'Đang tải...',
    'voucher.yourVouchers': 'Voucher của bạn',
    'voucher.expiryDate': 'HSD:',
    'voucher.usesLeft': 'Còn {count} lượt',
    'voucher.minOrder': 'Đơn tối thiểu:',
    'voucher.noLimit': 'Không giới hạn đơn',

    // Cart and Checkout
    'cart.title': 'Giỏ hàng',
    'cart.empty': 'Giỏ hàng của bạn đang trống',
    'cart.continueShopping': 'Tiếp tục mua sắm',
    'cart.checkout': 'Thanh toán',
    'cart.subtotal': 'Tạm tính',
    'cart.discount': 'Giảm giá',
    'cart.total': 'Tổng cộng',
    'cart.remove': 'Xóa',
    'cart.quantity': 'Số lượng',
    'cart.price': 'Giá',
    'cart.voucher': 'Mã giảm giá',
    'cart.applyVoucher': 'Áp dụng',
    'cart.apply': 'Áp dụng',
    'cart.enterCoupon': 'Nhập mã giảm giá',

    // Footer
    'footer.aboutLink': 'Giới thiệu',
    'footer.contactLink': 'Liên hệ',
    'footer.productsAndServices': 'Sản phẩm & Dịch vụ',
    'footer.products': 'Sản phẩm',
    'footer.services': 'Dịch vụ',
    'footer.testimonials': 'Đánh giá',
    'footer.navigationLinks': 'Điều hướng',
    'footer.pricing': 'Bảng giá',
    'footer.copyright': 'Bản quyền thuộc về công ty',
    'footer.acceptedPayments': 'Chấp nhận thanh toán',
    'footer.companyDescription1': 'XLab là công ty hàng đầu trong lĩnh vực phát triển giải pháp công nghệ và phần mềm chuyên nghiệp cho doanh nghiệp.',
    'footer.companyDescription2': 'Với đội ngũ chuyên gia giàu kinh nghiệm, XLab tự hào là đối tác tin cậy của hơn 500+ doanh nghiệp.',
    'footer.customers': '500+ Khách hàng',
    'footer.years': '5+ Năm',
    'footer.support': '24/7 Hỗ trợ',
    
    // Products page
    'products.title': 'Sản phẩm',
    'products.subtitle': 'Danh sách các phần mềm và dịch vụ chất lượng cao với mức giá tốt nhất thị trường.',
    'products.pageTitle': 'Phần mềm | XLab - Phần mềm và Dịch vụ',
    'products.all': 'Tất cả',
    'products.software': 'Phần mềm',
    'products.service': 'Dịch vụ',
    'products.showing': 'Hiển thị {count} kết quả',
    'products.sortBy': 'Sắp xếp',
    'products.sortNewest': 'Mới nhất',
    'products.sortPriceLow': 'Giá thấp đến cao',
    'products.sortPriceHigh': 'Giá cao đến thấp',
    'products.sortPopular': 'Phổ biến nhất',
    'products.sortRating': 'Đánh giá cao nhất',
    'products.loading': 'Đang tải sản phẩm...',
    'products.errorTitle': 'Không thể tải sản phẩm',
    'products.loadError': 'Không thể tải sản phẩm',
    'products.invalidData': 'Định dạng dữ liệu không hợp lệ',
    'products.error': 'Đã xảy ra lỗi',
    'products.tryAgain': 'Thử lại',
    'products.backToHome': 'Về trang chủ',
    'products.accounts': 'Tài khoản học tập',
    
    // Product detail page
    'product.details': 'Chi tiết sản phẩm',
    'product.specifications': 'Thông số kỹ thuật',
    'product.requirements': 'Yêu cầu hệ thống',
    'product.metaTitle': 'XLab - Phần mềm và Dịch vụ',
    'product.loading': 'Đang tải thông tin sản phẩm...',
    'product.version': 'Phiên bản',
    'product.quantity': 'Số lượng',
    'product.availableIn': 'Có sẵn trong',
    'product.price': 'Giá',
    'product.originalPrice': 'Giá gốc',
    'product.discount': 'Giảm',
    'product.relatedProducts': 'Sản phẩm liên quan',
    'product.relatedProductsSubtitle': 'Bạn có thể quan tâm đến những sản phẩm tương tự',
    'product.reviews': 'Đánh giá',
    'product.features': 'Tính năng',
    'product.description': 'Mô tả',
    'product.options': 'Loại',
    'product.selectOption': 'Chọn tùy chọn',
    'product.downloadCount': 'Lượt tải',
    'product.viewCount': 'Lượt xem',
    'product.addedToCart': 'Đã thêm {quantity} sản phẩm vào giỏ hàng',
    'product.outOfStock': 'Hết hàng',
    'product.inStock': 'Còn hàng',
    'product.tryDemo': 'Dùng thử',
    'product.free': 'Miễn phí',

    // Warranty page
    'warranty.title': 'Bảo Hành',
    'warranty.subtitle': 'XLab sẵn sàng hỗ trợ tư vấn và xử lý bảo hành suốt 365 ngày!',
    'warranty.policyTitle': 'Chính sách bảo hành',
    'warranty.periodTitle': 'Thời gian bảo hành',
    'warranty.period': 'XLab cam kết bảo hành cho tất cả các tài khoản và phần mềm trong thời hạn <strong>{days} ngày</strong> kể từ ngày mua.',
    'warranty.processTitle': 'Quy trình bảo hành',
    'warranty.process': 'Khi tài khoản gặp sự cố, quý khách vui lòng gửi yêu cầu hỗ trợ thông qua form bên cạnh hoặc liên hệ trực tiếp qua Zalo, Email.',
    'warranty.conditionsTitle': 'Điều kiện bảo hành',
    'warranty.conditions': 'Tài khoản phải nằm trong thời hạn bảo hành và được sử dụng đúng quy định.',
    'warranty.refundPolicyTitle': 'Chính sách đổi trả',
    'warranty.refundPeriodTitle': 'Thời gian đổi trả',
    'warranty.refundPeriod': 'Trong vòng <strong>{days} ngày</strong> kể từ ngày mua, quý khách có thể yêu cầu hoàn tiền nếu sản phẩm không đáp ứng được nhu cầu sử dụng.',
    'warranty.refundConditionsTitle': 'Điều kiện đổi trả',
    'warranty.refundConditions': 'Sản phẩm chưa bị sửa đổi, can thiệp và không vi phạm các điều khoản sử dụng.',
    'warranty.refundProcessTitle': 'Quy trình hoàn tiền',
    'warranty.refundProcess': 'Sau khi xác nhận yêu cầu hợp lệ, chúng tôi sẽ hoàn tiền qua phương thức thanh toán ban đầu trong vòng 3-5 ngày làm việc.',
    'warranty.supportRequestTitle': 'Yêu cầu hỗ trợ kỹ thuật',
    'warranty.submitSuccess': 'Cảm ơn bạn đã gửi yêu cầu! Chúng tôi sẽ phản hồi trong thời gian sớm nhất.',
    'warranty.formError': 'Có lỗi xảy ra khi gửi yêu cầu. Vui lòng thử lại sau.',
    'warranty.formName': 'Họ và tên',
    'warranty.formEmail': 'Email',
    'warranty.formPhone': 'Số điện thoại',
    'warranty.formOrderCode': 'Mã đơn hàng',
    'warranty.formAccountName': 'Tên tài khoản',
    'warranty.formProblem': 'Mô tả vấn đề',
    'warranty.formProblemPlaceholder': 'Mô tả chi tiết vấn đề bạn đang gặp phải',
    'warranty.formSubmitting': 'Đang gửi...',
    'warranty.formSubmit': 'Gửi yêu cầu hỗ trợ',
    'warranty.contactInfoTitle': 'Thông tin liên hệ',
    'warranty.supportInfo1': 'XLab hỗ trợ tư vấn mua hàng hoặc bảo hành từ <strong>8h00 đến 21h00 hàng ngày (kể cả ngày lễ)</strong>. Chúng tôi xử lý rất nhiều đơn hàng mỗi ngày và sẽ xử lý từng yêu cầu theo thứ tự. Chúng tôi sẽ hỗ trợ<strong> nhanh chóng trong vòng 24h</strong> sau khi nhận được yêu cầu.',
    'warranty.supportInfo2': 'Để được hỗ trợ bảo hành nhanh chóng, bạn vui lòng điền vấn đề cụ thể vào form yêu cầu hỗ trợ. Chúng tôi sẽ kiểm tra, hướng dẫn cách sửa lỗi hoặc gửi tài khoản mới tự động qua Email/Zalo của bạn.',
    'warranty.address': 'Địa chỉ',
    'warranty.workingHours': 'Giờ làm việc',
    'warranty.ourMission': 'Sứ mệnh của chúng tôi',
    'warranty.missionDescription': 'Sứ mệnh của XLab là đem đến cho người Việt cơ hội tiếp cận với các công cụ phục vụ làm việc, học tập, giải trí với giá cả phải chăng và chất lượng quốc tế.',
    'warranty.contactNow': 'Liên hệ ngay',
    'warranty.faq': 'Câu hỏi thường gặp',

    // Notifications
    'notifications.title': 'Thông báo',
    'notifications.markAllRead': 'Đánh dấu tất cả đã đọc',
    'notifications.noNotifications': 'Không có thông báo',
    
    // Orders
    'orders.myOrders': 'Đơn hàng của tôi',

    // Footer - Additional
    'footer.company': 'Công ty',
    'footer.careers': 'Tuyển dụng',
    'footer.terms': 'Điều khoản dịch vụ',
    'footer.privacy': 'Chính sách bảo mật',
    'footer.softwareDev': 'Phát triển phần mềm',
    'footer.consulting': 'Tư vấn công nghệ',
    'footer.cloudServices': 'Dịch vụ đám mây',
    'footer.techSupport': 'Hỗ trợ kỹ thuật',
    'footer.resources': 'Tài nguyên',
    'footer.blog': 'Blog',
    'footer.documentation': 'Tài liệu',
    'footer.faq': 'FAQ',
    'footer.followUs': 'Theo dõi chúng tôi',

    // Account page
    'account.myAccount': 'Tài khoản của tôi',
    'account.manageInfo': 'Quản lý thông tin cá nhân, giấy phép và lịch sử mua hàng của bạn.',
    'account.totalProducts': 'Tổng sản phẩm đã mua',
    'account.allActive': 'Tất cả đang hoạt động',
    'account.noProducts': 'Chưa có sản phẩm nào',
    'account.totalPaid': 'Tổng số tiền đã thanh toán',
    'account.throughOrders': 'Qua {count} đơn hàng',
    'account.totalSaved': 'Tổng số tiền đã tiết kiệm',
    'account.comparedToOriginal': 'So với giá gốc',
    'account.profile': 'Hồ sơ cá nhân',
    'account.personalInfo': 'Thông tin cá nhân',
    'account.fullName': 'Họ tên',
    'account.email': 'Email',
    'account.phone': 'Số điện thoại',
    'account.memberSince': 'Thành viên từ {date}',
    'account.updateInfo': 'Cập nhật thông tin',
    'account.notUpdated': 'Chưa cập nhật',
    'account.myProducts': 'Sản phẩm của tôi',
    'account.orders': 'Đơn hàng',
    'account.licenses': 'Giấy phép',
    'account.downloads': 'Tải xuống',
    'account.support': 'Hỗ trợ kỹ thuật',
    'account.settings': 'Cài đặt',
    'account.noLicenses': 'Không có giấy phép nào',
    'account.licenseDesc': 'Bạn chưa có giấy phép sản phẩm nào. Hãy mua sản phẩm để nhận giấy phép.',
    'account.licenseExpiry': 'Hạn giấy phép',
    'account.download': 'Tải xuống',
    'account.viewDetails': 'Xem chi tiết',
    'account.noDownloads': 'Không có tệp nào để tải xuống',
    'account.downloadDesc': 'Bạn cần mua sản phẩm trước khi có thể tải xuống phần mềm.',
    'account.version': 'Phiên bản: {version} (Cập nhật: {date})',
    'account.viewHistory': 'Xem lịch sử',
    'account.changePassword': 'Đổi mật khẩu',
    'account.currentPassword': 'Mật khẩu hiện tại',
    'account.newPassword': 'Mật khẩu mới',
    'account.confirmPassword': 'Xác nhận mật khẩu mới',
    'account.passwordChangeInstructions': 'Tính năng đổi mật khẩu chỉ hoạt động cho tài khoản đăng ký bằng email/mật khẩu. Tài khoản Google không hỗ trợ thay đổi mật khẩu qua trang này.',
    'account.coupons': 'Mã giảm giá đang sở hữu',
    'account.appliesToOrder': 'Áp dụng cho đơn hàng từ {amount}',
    'account.discountPercentage': 'Giảm {value}%{maxDiscount, select, undefined{} other{ (tối đa {maxDiscount})}}',
    'account.discountFixed': 'Giảm {value}',
    'account.noCoupons': 'Bạn chưa có mã giảm giá nào',
    'account.purchasedProducts': 'Sản phẩm đã mua',
    'coupon.welcome50': 'Welcome offer for new members',
    'coupon.xlabrnd10': 'Special 10% Discount',
    'coupon.member100k': '100K Discount for Members',
    'account.savingsFromSale': 'Tiết kiệm từ giá sale',
    'account.purchaseDate': 'Ngày mua',
    'account.savingsFromVoucher': 'Tiết kiệm từ voucher',
    'account.noProductsDescription': 'Bạn chưa mua sản phẩm nào. Khám phá các sản phẩm của chúng tôi để bắt đầu.',
    'account.exploreProducts': 'Khám phá sản phẩm',
    'account.product': 'Sản phẩm',
    'account.licenseKey': 'Mã giấy phép',
    'account.activationDate': 'Ngày kích hoạt',
    'account.expiryDate': 'Hạn sử dụng',
    'account.status': 'Trạng thái',
    'account.actions': 'Thao tác',
    'account.active': 'Đang hoạt động',
    'account.copy': 'Sao chép',
    'account.extend': 'Gia hạn',
    'account.noLicensesDescription': 'Bạn chưa có giấy phép sản phẩm nào. Hãy mua sản phẩm để nhận giấy phép.',
    'account.purchaseHistory': 'Lịch sử mua hàng',
    'account.viewAllOrders': 'Xem tất cả đơn hàng',
    'account.order': 'Đơn hàng #{id}',
    'account.orderDate': 'Ngày đặt: {date}',
    'account.totalSavings': 'Tổng tiết kiệm',
    'account.totalPayment': 'Tổng thanh toán: {amount}',
    'account.viewOrder': 'Chi tiết đơn hàng',
    'account.downloadPDF': 'Tải hóa đơn PDF',
    'account.noOrders': 'Chưa có đơn hàng nào',
    'account.noOrdersDescription': 'Bạn chưa thực hiện giao dịch nào. Hãy khám phá sản phẩm của chúng tôi.',
    'account.buyNow': 'Mua sắm ngay',
    'account.noDownloadsDescription': 'Bạn cần mua sản phẩm trước khi có thể tải xuống phần mềm.',
    'account.newRequest': 'Yêu cầu hỗ trợ mới',
    'account.supportDescription': 'Gửi yêu cầu hỗ trợ kỹ thuật cho sản phẩm bạn đã mua',
    'account.requestSuccess': 'Yêu cầu hỗ trợ của bạn đã được gửi thành công! Chúng tôi sẽ phản hồi sớm nhất có thể.',
    'account.selectProduct': 'Chọn sản phẩm cần hỗ trợ',
    'account.title': 'Tiêu đề',
    'account.enterTitle': 'Nhập tiêu đề vấn đề',
    'account.description': 'Mô tả vấn đề',
    'account.enterDescription': 'Mô tả chi tiết vấn đề bạn đang gặp phải',
    'account.formValidation': 'Vui lòng nhập đầy đủ thông tin',
    'account.submitRequest': 'Gửi yêu cầu hỗ trợ',
    'account.notifications': 'Thông báo',
    'account.settingsSaved': 'Cài đặt thông báo đã được lưu thành công!',
    'account.emailNotifications': 'Thông báo qua email',
    'account.productUpdates': 'Thông báo cập nhật sản phẩm',
    'account.promotions': 'Thông báo khuyến mãi và ưu đãi',
    'account.expiryReminders': 'Thông báo hết hạn giấy phép',
    'account.saveChanges': 'Lưu thay đổi',
    'account.logout': 'Đăng xuất',
    'account.endSession': 'Kết thúc phiên đăng nhập hiện tại của bạn',
    'account.accountDetails': 'Thông tin tài khoản',
    'account.saving': 'Đang lưu...',
    'account.infoUpdated': 'Thông tin đã được cập nhật thành công!',
    'account.quickStats': 'Thống kê nhanh',
    'account.activeLicenses': 'Giấy phép đang hoạt động',
    'account.purchasedOrders': 'Đơn hàng đã mua',
    'account.manageCoupons': 'Quản lý mã giảm giá',
    'account.manageLicenses': 'Quản lý giấy phép',
    'account.account': 'Tài khoản',
    'account.adminPanel': 'Quản trị viên',
    'account.deposit': 'Nạp tiền',
    'account.usedVouchers': 'Voucher đã dùng',
    'account.orderHistory': 'Lịch sử đơn hàng',
    'orders.history': 'Lịch sử đơn hàng của bạn',
    'orders.orderCode': 'Mã đơn hàng',
    'orders.orderDate': 'Ngày đặt',
    'orders.quantity': 'Số lượng',
    'orders.status': 'Trạng thái',
    'orders.total': 'Tổng cộng',
    'orders.viewDetails': 'Xem chi tiết',
    'orders.completed': 'Hoàn thành',
    'orders.pending': 'Chờ xử lý',
    'orders.processing': 'Đang xử lý',
    'orders.cancelled': 'Đã hủy',
    'orders.refunded': 'Hoàn tiền',
    'orders.noOrders': 'Bạn chưa có đơn hàng nào',
    'orders.exploreProducts': 'Xem sản phẩm',
    'orders.noOrdersDesc': 'Hãy khám phá các sản phẩm của chúng tôi và đặt hàng ngay!',
    'orders.needLogin': 'Bạn cần đăng nhập',
    'orders.needLoginDesc': 'Vui lòng đăng nhập để xem lịch sử đơn hàng của bạn',
    'orders.login': 'Đăng nhập',
    'notifications.none': 'Không có thông báo nào',
    'product.details': 'Chi tiết sản phẩm',
    'product.features': 'Tính năng',
    'product.frequentlyAskedQuestions': 'Câu hỏi thường gặp',
    'product.relatedProducts': 'Sản phẩm liên quan',
    'product.mightAlsoLike': 'Bạn có thể thích',
    'product.options': 'Tùy chọn',
    'testimonials.title': 'Đánh giá của khách hàng',
    'testimonials.verified': 'Đã xác minh',
    'home.testimonials': 'Đánh giá của khách hàng',
    'home.viewAllTestimonials': 'Xem tất cả đánh giá',
    'testimonial.michael': '"Tôi đã sử dụng dịch vụ của XLab được 2 năm và cực kỳ hài lòng. Phần mềm hoạt động mượt mà, có đầy đủ tính năng, và đội ngũ hỗ trợ rất tận tâm."',
    'testimonial.david': '"Các giải pháp AI của XLab đã giúp doanh nghiệp của chúng tôi tiết kiệm được 30% chi phí vận hành. Đội ngũ hỗ trợ kỹ thuật phản hồi nhanh chóng và hiệu quả."',
    'testimonial.emily': '"Các bản cập nhật liên tục của XLab đảm bảo sản phẩm luôn đáp ứng được những yêu cầu ngày càng cao của chúng tôi. Giao diện thân thiện và dễ sử dụng ngay cả với người mới."',
    'testimonial.position.business': 'Giám đốc kinh doanh',
    'testimonial.position.cto': 'CTO - Tech Solutions',
    'testimonial.position.project': 'Quản lý dự án',
    'cart.enterCoupon': 'Nhập mã giảm giá',

    // Testimonials page
    'testimonials.pageTitle': 'Đánh giá của khách hàng',
    'testimonials.pageSubtitle': 'Khám phá những trải nghiệm và kết quả thực tế mà khách hàng đã đạt được khi sử dụng giải pháp của XLab',
    'testimonials.clientsTab': 'Đánh giá từ khách hàng',
    'testimonials.caseStudiesTab': 'Các dự án tiêu biểu',
    'testimonials.videoTitle': 'Video đánh giá từ khách hàng',
    'testimonials.videoSubtitle': 'Xem video chia sẻ từ khách hàng về trải nghiệm sử dụng sản phẩm và dịch vụ của XLab',
    'testimonials.results': 'Kết quả đạt được:',
    'testimonials.cta.title': 'Sẵn sàng nâng tầm doanh nghiệp của bạn?',
    'testimonials.cta.description': 'Hãy liên hệ với chúng tôi ngay hôm nay để được tư vấn về giải pháp phù hợp nhất cho nhu cầu của bạn.',
    'testimonials.cta.contact': 'Liên hệ tư vấn',
    'testimonials.cta.explore': 'Khám phá dịch vụ',
    
    // User Notifications
    'notifications.title': 'Thông báo của bạn',
    'notifications.markAllRead': 'Đánh dấu tất cả đã đọc',
    'notifications.all': 'Tất cả',
    'notifications.unread': 'Chưa đọc',
    'notifications.viewDetails': 'Xem chi tiết',
    'notifications.viewNow': 'Xem ngay',
    'notifications.empty': 'Không có thông báo nào',
    'notifications.allRead': 'Bạn đã đọc tất cả thông báo!',
    'notifications.noNotifications': 'Bạn chưa có thông báo nào. Hãy quay lại sau.',
    'notifications.loading': 'Đang tải...',
    'notifications.backToHome': 'Quay lại trang chủ',
    'notifications.justNow': 'Vừa xong',
    'notifications.demo.title': 'Demo thông báo',
    'notifications.demo.description': 'Sử dụng công cụ này để tạo thông báo mới để test hệ thống thông báo của ứng dụng.',
    'notifications.demo.type': 'Loại thông báo',
    'notifications.demo.create': 'Tạo thông báo',
    'notifications.demo.note': 'Chú ý',
    'notifications.demo.noteText': 'Thông báo demo sẽ được thêm vào danh sách thông báo của bạn và sẽ được hiển thị ở Header. Trong môi trường thực tế, thông báo sẽ được tạo bởi hệ thống hoặc từ các hoạt động của người dùng.',
    'notifications.type.promotion': 'Khuyến mãi',
    'notifications.type.update': 'Cập nhật',
    'notifications.type.order': 'Đơn hàng',
    'notifications.type.system': 'Hệ thống',
    'notifications.demo.promotionTitle': 'Khuyến mãi mới',
    'notifications.demo.promotionContent': 'Khuyến mãi đặc biệt dành riêng cho bạn! Giảm 30% cho tất cả sản phẩm.',
    'notifications.demo.updateTitle': 'Cập nhật mới',
    'notifications.demo.updateContent': 'Phiên bản 2.0 đã ra mắt với nhiều tính năng mới',
    'notifications.demo.orderTitle': 'Đơn hàng mới',
    'notifications.demo.orderContent': 'Đơn hàng của bạn đã được xử lý và đang trong quá trình vận chuyển.',
    'notifications.demo.systemTitle': 'Thông báo hệ thống',
    'notifications.demo.systemContent': 'Hệ thống sẽ bảo trì vào lúc 22:00 tối nay. Xin lỗi vì sự bất tiện này.',
    
    // Admin Coupons
    'admin.coupons.title': 'Quản lý mã giảm giá',
    'admin.coupons.subtitle': 'Tạo và quản lý các mã giảm giá cho khách hàng',
    'admin.coupons.listTab': 'Danh sách mã',
    'admin.coupons.createTab': 'Tạo mã mới',
    'admin.coupons.totalCount': 'Tổng số mã',
    'admin.coupons.activeCount': 'Đang hoạt động',
    'admin.coupons.expiredCount': 'Đã hết hạn',
    'admin.coupons.listTitle': 'Danh sách mã giảm giá',
    'admin.coupons.activeTab': 'Đang hoạt động',
    'admin.coupons.expiredTab': 'Đã hết hạn',
    'admin.coupons.noCoUponsMessage': 'Tạo mã giảm giá đầu tiên để bắt đầu chương trình khuyến mãi cho khách hàng',
    'admin.coupons.createFirstButton': 'Tạo mã đầu tiên',
    'admin.coupons.codeColumn': 'Mã / Tên',
    'admin.coupons.typeColumn': 'Loại / Giá trị',
    'admin.coupons.timeColumn': 'Thời gian',
    'admin.coupons.usageColumn': 'Sử dụng',
    'admin.coupons.statusColumn': 'Trạng thái',
    'admin.coupons.actionsColumn': 'Hành động',
    'admin.coupons.percentageType': 'Phần trăm',
    'admin.coupons.fixedType': 'Cố định',
    'admin.coupons.cashbackType': 'Hoàn tiền vào tài khoản',
    'admin.coupons.createSuccess': 'Mã giảm giá đã được tạo thành công!',
    'admin.coupons.createError': 'Đã xảy ra lỗi khi tạo mã giảm giá',
    'admin.coupons.updateSuccess': 'Cập nhật thành công!',
    'admin.coupons.updateError': 'Có lỗi xảy ra khi cập nhật',
    'admin.coupons.fetchError': 'Không thể tải danh sách mã giảm giá',
    'admin.coupons.toggleError': 'Đã xảy ra lỗi khi cập nhật trạng thái',
    'admin.coupons.createTitle': 'Tạo mã giảm giá mới',
    'admin.coupons.timeAndConditions': 'Thời gian và điều kiện',
    'admin.coupons.validityPeriod': 'Thời gian hiệu lực',
    'admin.coupons.minOrder': 'Đơn hàng tối thiểu có thể sử dụng',
    'admin.coupons.status': 'Trạng thái',
    'admin.coupons.usageLimits': 'Giới hạn sử dụng',
    'admin.coupons.totalUsageLimit': 'Số lần sử dụng tối đa (0 = không giới hạn)',
    'admin.coupons.totalUsageDesc': 'Số lượt sử dụng được áp dụng cho toàn bộ mã giảm giá.',
    'admin.coupons.perUserLimit': 'Số lần mỗi người có thể sử dụng (0 = không giới hạn)',
    'admin.coupons.perUserLimitDesc': 'Giới hạn số lần mỗi người dùng có thể sử dụng mã giảm giá này.',
    'admin.coupons.createButton': 'Tạo mã giảm giá',
    'admin.coupons.public': 'Công khai',
    'admin.coupons.private': 'Riêng tư',
    'admin.coupons.edit': 'Sửa',
    'admin.coupons.delete': 'Xóa',
    'admin.coupons.stop': 'Dừng',
    'admin.coupons.clickToEdit': 'Click để chỉnh sửa',
    'admin.coupons.clickToEditType': 'Click để chỉnh sửa loại giảm giá',
    'admin.coupons.clickToEditUsage': 'Click để chỉnh sửa số lượt đã sử dụng',
    'admin.coupons.save': 'Lưu',
    'admin.coupons.cancel': 'Hủy',
    'admin.coupons.confirmDelete': 'Bạn có chắc chắn muốn xóa mã giảm giá này?',
    'admin.coupons.deleteSuccess': 'Mã giảm giá đã được xóa thành công!',
    'admin.coupons.deleteError': 'Đã xảy ra lỗi khi xóa mã giảm giá',
    'admin.coupons.activateSuccess': 'Mã giảm giá đã được kích hoạt thành công!',
    'admin.coupons.deactivateSuccess': 'Mã giảm giá đã được vô hiệu hóa thành công!',
    'admin.coupons.basicInfo': 'Thông tin cơ bản',
    'admin.coupons.code': 'Mã giảm giá',
    'admin.coupons.codePlaceholder': 'VD: SUMMER2024',
    'admin.coupons.generateAuto': 'Tạo tự động',
    'admin.coupons.name': 'Tên mã giảm giá',
    'admin.coupons.namePlaceholder': 'VD: Giảm giá mùa hè',
    'admin.coupons.typeAndValue': 'Loại và giá trị',
    'admin.coupons.type': 'Loại giảm giá',
    'admin.coupons.value': 'Giá trị giảm',
    'admin.coupons.minOrderDesc': 'Giá trị đơn hàng tối thiểu để áp dụng mã giảm giá.',
    'admin.coupons.expired': 'Đã hết hạn',
    'admin.coupons.active': 'Đang hoạt động',
    'admin.coupons.inactive': 'Tạm dừng',
    'admin.coupons.activate': 'Hoạt động',
    'admin.coupons.processing': 'Đang xử lý...',
    'admin.coupons.editTitle': 'Chỉnh sửa mã giảm giá:',
    'admin.coupons.updating': 'Đang cập nhật...',
    'admin.coupons.updateButton': 'Cập nhật',
    'admin.coupons.usageCount': 'lần',
  },
  en: {
    // Admin Notifications
    'admin.notifications.title': 'Notification Management',
    'admin.notifications.list': 'Notifications List',
    'admin.notifications.edit': 'Edit',
    'admin.notifications.settings': 'Settings',
    'admin.notifications.create': 'Create New Notification',
    'admin.notifications.noNotifications': 'No notifications yet',
    'admin.notifications.noNotificationsDesc': 'Create your first notification to send to users',
    'admin.notifications.type.promotion': 'Promotion',
    'admin.notifications.type.update': 'Update',
    'admin.notifications.type.order': 'Order',
    'admin.notifications.type.system': 'System',
    'admin.notifications.priority.high': 'High',
    'admin.notifications.priority.medium': 'Medium',
    'admin.notifications.priority.low': 'Low',
    'admin.notifications.created': 'Created',
    'admin.notifications.readCount': 'Read by',
    'admin.notifications.sentTo': 'Sent to',
    'admin.notifications.expires': 'Expires',
    'admin.notifications.viewDetails': 'View Details',
    'admin.notifications.editBtn': 'Edit',
    'admin.notifications.deleteBtn': 'Delete',
    'admin.notifications.cancelBtn': 'Cancel',
    'admin.notifications.createBtn': 'Create Notification',
    'admin.notifications.updatingBtn': 'Updating...',
    'admin.notifications.updateBtn': 'Update Notification',
    'admin.notifications.creatingBtn': 'Creating...',
    'admin.notifications.form.title': 'Notification Title *',
    'admin.notifications.form.titlePlaceholder': 'Enter notification title',
    'admin.notifications.form.content': 'Notification Content *',
    'admin.notifications.form.contentPlaceholder': 'Enter notification content',
    'admin.notifications.form.type': 'Notification Type *',
    'admin.notifications.settings.title': 'Notification Settings',
    'admin.notifications.settings.automatic': 'Automatic Notifications',
    'admin.notifications.settings.autoOrder': 'Automatic Order Notifications',
    'admin.notifications.settings.autoPromotion': 'Automatic Promotion Notifications',
    'admin.notifications.settings.autoUpdate': 'Automatic Update Notifications',
    'admin.notifications.settings.email': 'Email Notifications',
    'admin.notifications.settings.retention': 'Notification Retention Days',
    'admin.notifications.settings.retentionDesc': 'Notifications will be automatically deleted after this many days',
    'admin.notifications.settings.saveBtn': 'Save Settings',
    'admin.notifications.success': 'Notification created successfully!',
    'admin.notifications.updateSuccess': 'Notification updated successfully!',
    'admin.notifications.deleteSuccess': 'Notification deleted successfully!',
    'admin.notifications.settingsSaved': 'Notification settings have been saved!',
    'admin.notifications.error': 'An error occurred while creating the notification',
    'admin.notifications.updateError': 'An error occurred while updating the notification',
    'admin.notifications.deleteError': 'An error occurred while deleting the notification',
    'admin.notifications.connectionError': 'An error occurred while connecting to the server',
    'admin.notifications.people': 'people',
    
    // Terms page
    'terms.title': 'Terms of Service',
    'terms.lastUpdated': 'Last updated',
    'terms.section1.title': 'Introduction',
    'terms.section1.content': 'Welcome to {siteName}! These Terms of Service ("Terms") govern your access to and use of our website, products, and services. By accessing or using our services, you agree to these Terms.',
    'terms.section2.title': 'Your Account',
    'terms.section2.content': 'To use certain features of our services, you may need to create an account. You are responsible for maintaining the security of your account and password, and you are also responsible for all activities that occur under your account.',
    'terms.section3.title': 'Content and Intellectual Property',
    'terms.section3.content': '{companyName} and its licensors own all rights, title, and interest in the services, including all intellectual property rights. You may not copy, modify, distribute, or sell any part of our services without explicit written permission.',
    'terms.section4.title': 'License to Use',
    'terms.section4.content': '{companyName} grants you a personal, non-exclusive, non-transferable license to use our services. You may not copy, modify, distribute, sell, lease, rent, or sublicense any part of the services.',
    'terms.section5.title': 'Pricing and Payment',
    'terms.section5.content': 'For paid services, you agree to pay all applicable fees. We may change pricing by giving you advance notice. Payments are non-refundable unless otherwise specified in our refund policy.',
    'terms.section6.title': 'Privacy and Personal Data',
    'terms.section6.content': 'We collect and process your personal data according to our',
    'terms.section6.privacyPolicy': 'Privacy Policy',
    'terms.section6.content2': 'By using our services, you agree to the collection and processing of data in accordance with this policy.',
    'terms.section7.title': 'Disclaimer of Warranties',
    'terms.section7.content': 'Our services are provided "as is" and "as available". {companyName} disclaims all warranties, whether express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, and non-infringement.',
    'terms.section8.title': 'Limitation of Liability',
    'terms.section8.content': 'In no event will {companyName} be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, revenue, data, or business opportunities.',
    'terms.section9.title': 'Termination',
    'terms.section9.content': 'We may suspend or terminate your access to all or part of the services if you violate these Terms, or if we believe that your use may harm {companyName} or other users.',
    'terms.section10.title': 'Changes to Terms',
    'terms.section10.content': 'We may modify these Terms at any time. If we make material changes, we will notify you. Your continued use of our services after the changes take effect means you accept the new terms.',
    'terms.section11.title': 'Governing Law',
    'terms.section11.content': 'These Terms will be governed by and construed in accordance with the laws of Vietnam, regardless of conflict of legal principles.',
    'terms.section12.title': 'Contact',
    'terms.section12.content': 'If you have any questions about these Terms, please contact us at email:',
    'terms.section12.content2': 'or visit our',
    'terms.section12.contactPage': 'Contact',
    'terms.section12.content3': 'page.',

    // Header
    'nav.home': 'Home',
    'nav.products': 'Products',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.warranty': 'Warranty',
    'nav.login': 'Login',
    'nav.logout': 'Logout',
    'nav.account': 'Account',
    'nav.admin': 'Admin',
    'auth.signOut': 'Sign Out',
    'auth.signIn': 'Sign In',
    
    // Login page
    'login.welcome': 'Welcome back!',
    'login.continue': 'To continue using XLab services',
    'login.connect': 'Connect securely with your Google account',
    'login.google': 'Continue with Google',
    'login.secure': '100% Secure',
    'login.terms': 'By continuing, you agree to our',
    'login.termsLink': 'Terms of Service',
    'login.and': 'and',
    'login.privacyLink': 'Privacy Policy',
    'login.ourCompany': '.',
    
    // Homepage
    'home.slogan': 'Maximize efficiency, minimize costs!',
    'home.search': 'Search for software, applications...',
    'home.loadMore': 'Load more',
    'home.aboutTitle': 'About XLab',
    'home.aboutDesc1': 'XLab is a platform providing advanced AI-integrated software solutions that help users enhance productivity in work and daily life.',
    'home.aboutDesc2': 'Our mission is to provide Vietnamese people with access to tools for work, study, and entertainment at reasonable prices and international quality.',
    'home.learnMore': 'Learn more',
    'home.domesticProduct': 'Domestic Products',
    'home.vietnamDevs': 'Developed by Vietnamese engineers',
    'home.support247': '24/7 Support',
    'home.supportTeam': 'Dedicated support team',
    'home.highSecurity': 'High Security',
    'home.encryptedData': 'Securely encrypted data',
    'home.reasonablePrice': 'Reasonable Pricing',
    'home.budgetOptions': 'Multiple options for any budget',
    'home.aiIntegration': 'AI Integration',
    'home.aiSupport': 'Advanced AI technology to support you',
    'home.continuousUpdates': 'Continuous Updates',
    'home.newFeatures': 'Always updated with new features',
    'home.achievements': 'Our Achievements',
    'home.customers': 'Trusted customers',
    'home.softwareSolutions': 'Software solutions',
    'home.yearsExperience': 'Years of experience',
    'home.software': 'Software',
    'home.services': 'Services',
    'home.featuredProducts': 'Featured Products',
    'home.newProducts': 'New Products',
    'home.viewAll': 'View all',
    'home.noSoftware': 'No software yet',
    'home.updateSoon': 'We will update our software soon.',
    'home.noServices': 'No services yet',
    'home.updateServices': 'We will update our services soon.',
    'home.faq': 'Frequently Asked Questions',
    'home.faqDesc': 'Answers to common questions from customers about XLab products and services',
    'home.faq1Title': 'How do I download software?',
    'home.faq1Desc': 'You can download free software from the corresponding product page after logging into your account. For paid products, you need to complete payment before downloading.',
    'home.faq2Title': 'How do I activate the license?',
    'home.faq2Desc': 'After purchasing, you will receive an activation code by email. Open the application, go to "Activate License" and enter this code to use all features.',
    'home.faq3Title': 'How many devices can I use?',
    'home.faq3Desc': 'Each license allows you to use up to 3 different devices. If you want to use more devices, please purchase additional licenses or upgrade to a business plan.',
    'home.faq4Title': 'What is the refund policy?',
    'home.faq4Desc': 'We have a 7-day refund policy from the purchase date if the product does not meet your needs. Contact our support team for guidance.',
    'home.faq5Title': 'How do I contact technical support?',
    'home.faq5Desc': 'You can contact our technical support team via email at support@xlab.vn, hotline 1900.xxxx, or chat directly on the website. We respond within 24 business hours.',
    'home.faq6Title': 'Does XLab provide enterprise solutions?',
    'home.faq6Desc': 'Yes, we offer special service packages for businesses with pricing benefits and specialized technical support. Contact us for the most suitable solution.',
    'home.moreQuestions': 'View more questions',
    'home.ctaTitle': 'Ready to boost your productivity with XLab?',
    'home.ctaDesc': 'We offer special discounts for customers who purchase in bulk. The more you buy, the higher the discount. We are committed to bringing you the best solutions at the most reasonable cost.',
    'home.contactUs': 'Contact us',
    
    // Product card
    'product.addToCart': 'Add to cart',
    'product.buyNow': 'Buy now',
    'product.added': 'Added',
    'product.week': 'week',
    'product.purchasesPerWeek': '{count}/week',
    
    // About page
    'about.title': 'About XLab',
    'about.subtitle': 'Accompanying your business in the digital transformation journey',
    'about.values': 'Our core values',
    'about.innovation': 'Innovation',
    'about.innovationDesc': 'Continuously create and innovate technology to deliver the best value',
    'about.quality': 'Quality',
    'about.qualityDesc': 'Commitment to the highest quality in all products and services',
    'about.integrity': 'Integrity',
    'about.integrityDesc': 'Always maintain business ethics and transparency in all activities',
    'about.collaboration': 'Collaboration',
    'about.collaborationDesc': 'Building long-term partnerships based on respect and mutually beneficial cooperation',
    'about.partnership': 'Partner with XLab',
    'about.partnershipDesc': 'We are always ready to listen and accompany your business in the journey of digital transformation and sustainable development.',
    'about.contactNow': 'Contact Now',
    'about.exploreServices': 'Explore Services',

    // About page - Additional keys
    'about.pageTitle': 'About Us',
    'about.pageSubtitle': 'XLab - A pioneer in software development and technology solutions in Vietnam',
    'about.ourStory': 'Our Story',
    'about.storyP1': 'XLab was founded in 2018 by a group of passionate software engineers with a vision of creating advanced technology solutions to help Vietnamese businesses improve operational efficiency and competitiveness in the digital era.',
    'about.storyP2': 'After more than 10 years of operation and development, XLab has become a trusted technology partner for hundreds of businesses at home and abroad, from startups to large corporations in various fields such as finance, retail, manufacturing, education and healthcare.',
    'about.storyP3': 'We are proud of our talented and technology-passionate team, with more than 100 software experts, system engineers, and experienced consultants, always dedicated to the goal of providing optimal solutions for partners and customers.',
    'about.mission': 'Mission',
    'about.missionDesc': 'XLab\'s mission is to apply advanced technology to create excellent software solutions, helping Vietnamese businesses optimize processes, increase productivity and develop sustainably in the digital era. We are committed to delivering high-quality products and services that meet the diverse needs of our customers, while contributing to the development of Vietnam\'s information technology industry.',
    'about.vision': 'Vision',
    'about.visionDesc': 'XLab aims to become a leading technology company in Vietnam and the Southeast Asian region in software development and comprehensive IT solution provision. We strive to be a trusted and long-term partner for businesses in the digital transformation journey, as well as an ideal working environment for technology talents to develop their careers.',
    'about.coreValues': 'Core Values',
    'about.coreValuesDesc': 'The values that shape XLab\'s culture and guide all activities',
    'about.value1': 'Quality',
    'about.value1Desc': 'Put product and service quality first, continuously improve to achieve excellence',
    'about.value2': 'Innovation',
    'about.value2Desc': 'Encourage creative thinking, dare to experiment with new ideas and advanced technologies',
    'about.value3': 'Collaboration',
    'about.value3Desc': 'Build long-term partnerships based on respect and mutually beneficial cooperation',
    'about.value4': 'Responsibility',
    'about.value4Desc': 'Work with high responsibility, committed to fulfilling all commitments to customers',
    
    // Contact page
    'contact.title': 'Contact Us',
    'contact.subtitle': 'We\'re here to help and answer any question you might have',
    'contact.pageTitle': 'Contact | XLab - Software and Services',
    'contact.pageSubtitle': 'Contact us to get advice on the best solution for your business',
    'contact.sendMessage': 'Send us a message',
    'contact.yourName': 'Your Name',
    'contact.yourEmail': 'Your Email',
    'contact.yourPhone': 'Phone Number',
    'contact.yourCompany': 'Company',
    'contact.serviceInterest': 'Service of Interest',
    'contact.selectService': '-- Select Service --',
    'contact.softwareDev': 'Software Development',
    'contact.cloudServices': 'Cloud Services',
    'contact.consulting': 'Technology Consulting',
    'contact.techSupport': 'Technical Support',
    'contact.other': 'Other',
    'contact.message': 'Message',
    'contact.send': 'Send Message',
    'contact.sending': 'Sending...',
    'contact.info': 'Contact Information',
    'contact.address': 'Address',
    'contact.email': 'Email',
    'contact.phone': 'Phone',
    'contact.connectWithUs': 'Connect With Us',
    'contact.required': 'Required',
    'contact.successMessage': 'Thank you for contacting us! We will respond as soon as possible.',
    'contact.errorMessage': 'An error occurred while submitting the form. Please try again later.',
    'contact.callUs': 'Call Us',
    'contact.emailUs': 'Email Us',
    'contact.visitUs': 'Visit Us',
    'contact.workingHours': 'Working Hours',
    'contact.faq': 'Frequently Asked Questions',
    'contact.faqSubtitle': 'Find quick answers to common questions',
    'contact.followUs': 'Follow us on social media',
    'contact.newsletterTitle': 'Subscribe to Our Newsletter',
    'contact.newsletterSubtitle': 'Get the latest news and updates',
    'contact.newsletterPlaceholder': 'Enter your email',
    'contact.newsletterSubmit': 'Subscribe',
    'contact.monday': 'Monday',
    'contact.tuesday': 'Tuesday',
    'contact.wednesday': 'Wednesday',
    'contact.thursday': 'Thursday',
    'contact.friday': 'Friday',
    'contact.saturday': 'Saturday',
    'contact.sunday': 'Sunday',
    'contact.closed': 'Closed',

    // Common buttons
    'button.getStarted': 'Get Started',
    'button.learnMore': 'Learn More',
    'button.viewDetails': 'View Details',
    'button.addToCart': 'Add to Cart',
    'button.buyNow': 'Buy Now',
    'button.download': 'Download',
    'button.contactUs': 'Contact Us',
    'button.viewAll': 'View All',

    // Voucher widget
    'voucher.title': 'Discount Code',
    'voucher.viewAll': 'View all',
    'voucher.loading': 'Loading...',
    'voucher.yourVouchers': 'Your Vouchers',
    'voucher.expiryDate': 'Expiry:',
    'voucher.usesLeft': 'Uses left: {count}',
    'voucher.minOrder': 'Minimum order:',
    'voucher.noLimit': 'No limit',

    // Cart and Checkout
    'cart.title': 'Shopping Cart',
    'cart.empty': 'Your cart is empty',
    'cart.continueShopping': 'Continue Shopping',
    'cart.checkout': 'Checkout',
    'cart.subtotal': 'Subtotal',
    'cart.discount': 'Discount',
    'cart.total': 'Total',
    'cart.remove': 'Remove',
    'cart.quantity': 'Quantity',
    'cart.price': 'Price',
    'cart.voucher': 'Discount Code',
    'cart.applyVoucher': 'Apply',
    'cart.apply': 'Apply',
    'cart.enterCoupon': 'Enter coupon code',

    // Footer
    'footer.aboutLink': 'About XLab',
    'footer.contactLink': 'Contact',
    'footer.productsAndServices': 'Products & Services',
    'footer.products': 'Products',
    'footer.services': 'Services',
    'footer.testimonials': 'Testimonials',
    'footer.navigationLinks': 'Navigation',
    'footer.pricing': 'Pricing',
    'footer.copyright': 'Copyright owned by',
    'footer.acceptedPayments': 'Accepted Payments',
    'footer.companyDescription1': 'XLab is a leading company in the field of technology solutions and professional software development for businesses.',
    'footer.companyDescription2': 'With a team of experienced experts, XLab is proud to be a trusted partner of over 500+ businesses.',
    'footer.customers': '500+ Customers',
    'footer.years': '5+ Years',
    'footer.support': '24/7 Support',
    
    // Products page
    'products.title': 'Products',
    'products.subtitle': 'List of high-quality software and services with the best prices on the market.',
    'products.pageTitle': 'Software | XLab - Software and Services',
    'products.all': 'All',
    'products.software': 'Software',
    'products.service': 'Service',
    'products.showing': 'Showing {count} results',
    'products.sortBy': 'Sort by',
    'products.sortNewest': 'Newest',
    'products.sortPriceLow': 'Price: Low to High',
    'products.sortPriceHigh': 'Price: High to Low',
    'products.sortPopular': 'Most Popular',
    'products.sortRating': 'Highest Rated',
    'products.loading': 'Loading products...',
    'products.errorTitle': 'Unable to load products',
    'products.loadError': 'Unable to load products',
    'products.invalidData': 'Invalid data format',
    'products.error': 'An error occurred',
    'products.tryAgain': 'Try Again',
    'products.backToHome': 'Back to Home',
    'products.accounts': 'Learning Accounts',
    
    // Product detail page
    'product.details': 'Product Details',
    'product.specifications': 'Technical Specifications',
    'product.requirements': 'System Requirements',
    'product.metaTitle': 'XLab - Software and Services',
    'product.loading': 'Loading product information...',
    'product.version': 'Version',
    'product.quantity': 'Quantity',
    'product.availableIn': 'Available in',
    'product.price': 'Price',
    'product.originalPrice': 'Original Price',
    'product.discount': 'Discount',
    'product.relatedProducts': 'Related Products',
    'product.relatedProductsSubtitle': 'You may be interested in similar products',
    'product.reviews': 'Reviews',
    'product.features': 'Features',
    'product.description': 'Description',
    'product.options': 'Options',
    'product.selectOption': 'Select option',
    'product.downloadCount': 'Downloads',
    'product.viewCount': 'Views',
    'product.addedToCart': 'Added {quantity} product(s) to cart',
    'product.outOfStock': 'Out of stock',
    'product.inStock': 'In stock',
    'product.tryDemo': 'Try demo',
    'product.free': 'Free',

    // Warranty page
    'warranty.title': 'Warranty',
    'warranty.subtitle': 'XLab is ready to provide consultation and warranty service for 365 days!',
    'warranty.policyTitle': 'Warranty Policy',
    'warranty.periodTitle': 'Warranty Period',
    'warranty.period': 'XLab guarantees warranty for all accounts and software for <strong>{days} days</strong> from the date of purchase.',
    'warranty.processTitle': 'Warranty Process',
    'warranty.process': 'When your account encounters issues, please send a support request through the form on the side or contact us directly via Zalo, Email.',
    'warranty.conditionsTitle': 'Warranty Conditions',
    'warranty.conditions': 'The account must be within the warranty period and used according to regulations.',
    'warranty.refundPolicyTitle': 'Refund Policy',
    'warranty.refundPeriodTitle': 'Refund Period',
    'warranty.refundPeriod': 'Within <strong>{days} days</strong> from the date of purchase, you can request a refund if the product does not meet your needs.',
    'warranty.refundConditionsTitle': 'Refund Conditions',
    'warranty.refundConditions': 'The product has not been modified, tampered with, and does not violate the terms of use.',
    'warranty.refundProcessTitle': 'Refund Process',
    'warranty.refundProcess': 'After confirming the valid request, we will refund through the original payment method within 3-5 business days.',
    'warranty.supportRequestTitle': 'Technical Support Request',
    'warranty.submitSuccess': 'Thank you for submitting your request! We will respond as soon as possible.',
    'warranty.formError': 'An error occurred while submitting the request. Please try again later.',
    'warranty.formName': 'Full Name',
    'warranty.formEmail': 'Email',
    'warranty.formPhone': 'Phone Number',
    'warranty.formOrderCode': 'Order Code',
    'warranty.formAccountName': 'Account Name',
    'warranty.formProblem': 'Issue Description',
    'warranty.formProblemPlaceholder': 'Describe the issue you are experiencing in detail',
    'warranty.formSubmitting': 'Submitting...',
    'warranty.formSubmit': 'Submit Support Request',
    'warranty.contactInfoTitle': 'Contact Information',
    'warranty.supportInfo1': 'XLab provides purchase or warranty consultation from <strong>8:00 AM to 9:00 PM daily (including holidays)</strong>. We process many orders every day and will process each request in order. We will provide <strong>quick support within 24 hours</strong> after receiving the request.',
    'warranty.supportInfo2': 'For fast warranty support, please fill in the specific issue in the support request form. We will check, guide how to fix the error, or send a new account automatically via your Email/Zalo.',
    'warranty.address': 'Address',
    'warranty.workingHours': 'Working Hours',
    'warranty.ourMission': 'Our Mission',
    'warranty.missionDescription': 'XLab\'s mission is to provide Vietnamese people with access to tools for work, study, and entertainment at reasonable prices and international quality.',
    'warranty.contactNow': 'Contact Now',
    'warranty.faq': 'Frequently Asked Questions',

    // Notifications
    'notifications.title': 'Notifications',
    'notifications.markAllRead': 'Mark all as read',
    'notifications.noNotifications': 'No notifications',
    
    // Orders
    'orders.myOrders': 'My Orders',

    // Footer - Additional
    'footer.company': 'Company',
    'footer.careers': 'Careers',
    'footer.terms': 'Terms of Service',
    'footer.privacy': 'Privacy Policy',
    'footer.softwareDev': 'Software Development',
    'footer.consulting': 'Technology Consulting',
    'footer.cloudServices': 'Cloud Services',
    'footer.techSupport': 'Technical Support',
    'footer.resources': 'Resources',
    'footer.blog': 'Blog',
    'footer.documentation': 'Documentation',
    'footer.faq': 'FAQ',
    'footer.followUs': 'Follow Us',

    // Account page
    'account.myAccount': 'My Account',
    'account.manageInfo': 'Manage your personal information, licenses and purchase history.',
    'account.totalProducts': 'Total Products Purchased',
    'account.allActive': 'All active',
    'account.noProducts': 'No products yet',
    'account.totalPaid': 'Total Amount Paid',
    'account.throughOrders': 'Through {count} orders',
    'account.totalSaved': 'Total Amount Saved',
    'account.comparedToOriginal': 'Compared to original price',
    'account.profile': 'Personal Profile',
    'account.personalInfo': 'Personal Information',
    'account.fullName': 'Full Name',
    'account.email': 'Email',
    'account.phone': 'Phone Number',
    'account.memberSince': 'Member since {date}',
    'account.updateInfo': 'Update Information',
    'account.notUpdated': 'Not updated',
    'account.myProducts': 'My Products',
    'account.orders': 'Orders',
    'account.licenses': 'Licenses',
    'account.downloads': 'Downloads',
    'account.support': 'Technical Support',
    'account.settings': 'Settings',
    'account.noLicenses': 'No licenses',
    'account.licenseDesc': 'You don\'t have any product licenses yet. Purchase a product to get a license.',
    'account.licenseExpiry': 'License Expiry',
    'account.download': 'Download',
    'account.viewDetails': 'View Details',
    'account.noDownloads': 'No files to download',
    'account.downloadDesc': 'You need to purchase a product before you can download software.',
    'account.version': 'Version: {version} (Updated: {date})',
    'account.viewHistory': 'View History',
    'account.changePassword': 'Change Password',
    'account.currentPassword': 'Current Password',
    'account.newPassword': 'New Password',
    'account.confirmPassword': 'Confirm New Password',
    'account.passwordChangeInstructions': 'Password change feature only works for accounts registered with email/password. Google accounts do not support password changes through this page.',
    'account.coupons': 'My Coupons',
    'account.appliesToOrder': 'Applies to orders from {amount}',
    'account.discountPercentage': '{value}% off{maxDiscount, select, undefined{} other{ (max {maxDiscount})}}',
    'account.discountFixed': '{value} off',
    'account.noCoupons': 'You don\'t have any coupons yet',
    'coupon.welcome50': 'New Member Welcome',
    'coupon.xlabrnd10': 'Exclusive 10% Discount',
    'coupon.member100k': '100K Member Discount',
    'account.purchasedProducts': 'Purchased Products',
    'account.price': 'Price',
    'account.savingsFromSale': 'Savings from sale',
    'account.purchaseDate': 'Purchase date',
    'account.savingsFromVoucher': 'Savings from voucher',
    'account.noProductsDescription': 'You haven\'t purchased any products yet. Explore our products to get started.',
    'account.exploreProducts': 'Explore Products',
    'account.product': 'Product',
    'account.licenseKey': 'License Key',
    'account.activationDate': 'Activation Date',
    'account.expiryDate': 'Expiry Date',
    'account.status': 'Status',
    'account.actions': 'Actions',
    'account.active': 'Active',
    'account.copy': 'Copy',
    'account.extend': 'Extend',
    'account.noLicensesDescription': 'You don\'t have any product licenses yet. Purchase a product to get a license.',
    'account.purchaseHistory': 'Purchase History',
    'account.viewAllOrders': 'View all orders',
    'account.order': 'Order #{id}',
    'account.orderDate': 'Order date: {date}',
    'account.totalSavings': 'Total savings',
    'account.totalPayment': 'Total payment: {amount}',
    'account.viewOrder': 'View order details',
    'account.downloadPDF': 'Download PDF invoice',
    'account.noOrders': 'No orders yet',
    'account.noOrdersDescription': 'You haven\'t made any transactions yet. Explore our products.',
    'account.buyNow': 'Shop Now',
    'account.noDownloadsDescription': 'You need to purchase a product before you can download software.',
    'account.newRequest': 'New Support Request',
    'account.supportDescription': 'Submit a technical support request for products you have purchased',
    'account.requestSuccess': 'Your support request has been successfully submitted! We will respond as soon as possible.',
    'account.selectProduct': 'Select product for support',
    'account.title': 'Title',
    'account.enterTitle': 'Enter issue title',
    'account.description': 'Issue Description',
    'account.enterDescription': 'Describe the issue you are experiencing in detail',
    'account.formValidation': 'Please fill in all required information',
    'account.submitRequest': 'Submit Support Request',
    'account.notifications': 'Notifications',
    'account.settingsSaved': 'Notification settings have been saved successfully!',
    'account.emailNotifications': 'Email notifications',
    'account.productUpdates': 'Product update notifications',
    'account.promotions': 'Promotions and special offers',
    'account.expiryReminders': 'License expiry reminders',
    'account.saveChanges': 'Save Changes',
    'account.logout': 'Logout',
    'account.endSession': 'End your current session',
    'account.accountDetails': 'Account Details',
    'account.saving': 'Saving...',
    'account.infoUpdated': 'Information updated successfully!',
    'account.quickStats': 'Quick Stats',
    'account.activeLicenses': 'Active Licenses',
    'account.purchasedOrders': 'Purchased Orders',
    'account.manageCoupons': 'Manage Coupons',
    'account.manageLicenses': 'Manage Licenses',
    'account.account': 'Account',
    'account.adminPanel': 'Administrator',
    'account.deposit': 'Deposit',
    'account.usedVouchers': 'Used Vouchers',
    'account.orderHistory': 'Order History',
    'orders.history': 'Your Order History',
    'orders.orderCode': 'Order Code',
    'orders.orderDate': 'Order Date',
    'orders.quantity': 'Quantity',
    'orders.status': 'Status',
    'orders.total': 'Total',
    'orders.viewDetails': 'View Details',
    'orders.completed': 'Completed',
    'orders.pending': 'Pending',
    'orders.processing': 'Processing',
    'orders.cancelled': 'Cancelled',
    'orders.refunded': 'Refunded',
    'orders.noOrders': 'You have no orders yet',
    'orders.exploreProducts': 'Browse Products',
    'orders.noOrdersDesc': 'Explore our products and place an order now!',
    'orders.needLogin': 'Login Required',
    'orders.needLoginDesc': 'Please login to view your order history',
    'orders.login': 'Login',
    'notifications.none': 'No notifications',
    'product.details': 'Product details',
    'product.features': 'Features',
    'product.frequentlyAskedQuestions': 'Frequently Asked Questions',
    'product.relatedProducts': 'Related products',
    'product.mightAlsoLike': 'You might also like',
    'product.options': 'Options',
    'testimonials.title': 'Customer Reviews',
    'testimonials.verified': 'Verified',
    'testimonials.positions.CTO': 'Chief Technology Officer',
    'testimonials.positions.CTO - Tech Solutions': 'Chief Technology Officer',
    'testimonials.positions.Marketing Manager': 'Marketing Manager',
    'testimonials.positions.Developer': 'Developer',
    'testimonials.companies.Tech Solutions': 'Tech Solutions',
    'testimonials.companies.Digital Agency': 'Digital Agency',
    'testimonials.companies.Software Inc.': 'Software Inc.',
    'testimonial.position.project': 'Project Manager',
    'testimonial.position.business': 'Business Director',
    'testimonial.position.cto': 'CTO - Tech Solutions',

    // Testimonials page
    'testimonials.pageTitle': 'Customer Reviews',
    'testimonials.pageSubtitle': 'Discover the experiences and real results that customers have achieved using XLab solutions',
    'testimonials.clientsTab': 'Client Testimonials',
    'testimonials.caseStudiesTab': 'Case Studies',
    'testimonials.videoTitle': 'Video Testimonials',
    'testimonials.videoSubtitle': 'Watch videos from customers sharing their experience using XLab products and services',
    'testimonials.results': 'Results achieved:',
    'testimonials.cta.title': 'Ready to elevate your business?',
    'testimonials.cta.description': 'Contact us today for a consultation about the most suitable solution for your needs.',
    'testimonials.cta.contact': 'Contact Us',
    'testimonials.cta.explore': 'Explore Our Services',
    
    // User Notifications
    'notifications.title': 'Your Notifications',
    'notifications.markAllRead': 'Mark all as read',
    'notifications.all': 'All',
    'notifications.unread': 'Unread',
    'notifications.viewDetails': 'View details',
    'notifications.viewNow': 'View now',
    'notifications.empty': 'No notifications',
    'notifications.allRead': 'You have read all notifications!',
    'notifications.noNotifications': 'You don\'t have any notifications yet. Please check back later.',
    'notifications.loading': 'Loading...',
    'notifications.backToHome': 'Back to home',
    'notifications.justNow': 'Just now',
    'notifications.demo.title': 'Notification Demo',
    'notifications.demo.description': 'Use this tool to create new notifications to test the notification system.',
    'notifications.demo.type': 'Notification type',
    'notifications.demo.create': 'Create notification',
    'notifications.demo.note': 'Note',
    'notifications.demo.noteText': 'Demo notifications will be added to your notification list and will be displayed in the Header. In a real environment, notifications will be created by the system or from user activities.',
    'notifications.type.promotion': 'Promotion',
    'notifications.type.update': 'Update',
    'notifications.type.order': 'Order',
    'notifications.type.system': 'System',
    'notifications.demo.promotionTitle': 'New promotion',
    'notifications.demo.promotionContent': 'Special promotion just for you! 30% off all products.',
    'notifications.demo.updateTitle': 'New update',
    'notifications.demo.updateContent': 'Version 2.0 has been released with many new features',
    'notifications.demo.orderTitle': 'New order',
    'notifications.demo.orderContent': 'Your order has been processed and is being shipped.',
    'notifications.demo.systemTitle': 'System notification',
    'notifications.demo.systemContent': 'The system will undergo maintenance at 10:00 PM tonight. We apologize for any inconvenience.',
    
    // Admin Coupons
    'admin.coupons.title': 'Coupon Management',
    'admin.coupons.subtitle': 'Create and manage discount coupons for customers',
    'admin.coupons.listTab': 'Coupon List',
    'admin.coupons.createTab': 'Create New Coupon',
    'admin.coupons.totalCount': 'Total Coupons',
    'admin.coupons.activeCount': 'Active',
    'admin.coupons.expiredCount': 'Expired',
    'admin.coupons.listTitle': 'Coupon List',
    'admin.coupons.activeTab': 'Active',
    'admin.coupons.expiredTab': 'Expired',
    'admin.coupons.noCoUponsMessage': 'Create your first coupon to start offering promotions to customers',
    'admin.coupons.createFirstButton': 'Create First Coupon',
    'admin.coupons.codeColumn': 'Code / Name',
    'admin.coupons.typeColumn': 'Type / Value',
    'admin.coupons.timeColumn': 'Time Period',
    'admin.coupons.usageColumn': 'Usage',
    'admin.coupons.statusColumn': 'Status',
    'admin.coupons.actionsColumn': 'Actions',
    'admin.coupons.percentageType': 'Percentage',
    'admin.coupons.fixedType': 'Fixed Amount',
    'admin.coupons.cashbackType': 'Account Credit',
    'admin.coupons.createSuccess': 'Coupon created successfully!',
    'admin.coupons.createError': 'An error occurred while creating the coupon',
    'admin.coupons.updateSuccess': 'Updated successfully!',
    'admin.coupons.updateError': 'An error occurred while updating',
    'admin.coupons.fetchError': 'Could not load coupon list',
    'admin.coupons.toggleError': 'An error occurred while updating status',
    'admin.coupons.createTitle': 'Create New Coupon',
    'admin.coupons.timeAndConditions': 'Time and Conditions',
    'admin.coupons.validityPeriod': 'Validity Period',
    'admin.coupons.minOrder': 'Minimum Order Value',
    'admin.coupons.status': 'Status',
    'admin.coupons.usageLimits': 'Usage Limits',
    'admin.coupons.totalUsageLimit': 'Maximum Usage Count (0 = unlimited)',
    'admin.coupons.totalUsageDesc': 'Usage count applies to the entire coupon.',
    'admin.coupons.perUserLimit': 'Uses Per Customer (0 = unlimited)',
    'admin.coupons.perUserLimitDesc': 'Limit how many times each user can use this coupon.',
    'admin.coupons.createButton': 'Create Coupon',
    'admin.coupons.public': 'Public',
    'admin.coupons.private': 'Private',
    'admin.coupons.edit': 'Edit',
    'admin.coupons.delete': 'Delete',
    'admin.coupons.stop': 'Stop',
    'admin.coupons.clickToEdit': 'Click to edit',
    'admin.coupons.clickToEditType': 'Click to edit discount type',
    'admin.coupons.clickToEditUsage': 'Click to edit usage count',
    'admin.coupons.save': 'Save',
    'admin.coupons.cancel': 'Cancel',
    'admin.coupons.confirmDelete': 'Are you sure you want to delete this coupon?',
    'admin.coupons.deleteSuccess': 'Coupon has been deleted successfully!',
    'admin.coupons.deleteError': 'An error occurred while deleting the coupon',
    'admin.coupons.activateSuccess': 'Coupon has been activated successfully!',
    'admin.coupons.deactivateSuccess': 'Coupon has been deactivated successfully!',
    'admin.coupons.basicInfo': 'Basic Information',
    'admin.coupons.code': 'Coupon Code',
    'admin.coupons.codePlaceholder': 'Ex: SUMMER2024',
    'admin.coupons.generateAuto': 'Generate automatically',
    'admin.coupons.name': 'Coupon Name',
    'admin.coupons.namePlaceholder': 'Ex: Summer Discount',
    'admin.coupons.typeAndValue': 'Type and Value',
    'admin.coupons.type': 'Discount Type',
    'admin.coupons.value': 'Discount Value',
    'admin.coupons.minOrderDesc': 'Minimum order value to apply this coupon.',
    'admin.coupons.expired': 'Expired',
    'admin.coupons.active': 'Active', 
    'admin.coupons.inactive': 'Inactive',
    'admin.coupons.activate': 'Activate',
    'admin.coupons.processing': 'Processing...',
    'admin.coupons.editTitle': 'Edit Coupon:',
    'admin.coupons.updating': 'Updating...',
    'admin.coupons.updateButton': 'Update',
    'admin.coupons.usageCount': 'uses',
  },
};

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  // Mặc định là tiếng Việt
  const [language, setLanguageState] = useState<Language>('vi');

  // Khởi tạo ngôn ngữ từ localStorage khi component được mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem('language');
    if (savedLanguage && (savedLanguage === 'vi' || savedLanguage === 'en')) {
      setLanguageState(savedLanguage);
    }
  }, []);

  // Lưu ngôn ngữ vào localStorage khi thay đổi
  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
    document.documentElement.lang = lang;
  };

  // Hàm dịch văn bản
  const t = (key: string, params?: Record<string, any>): string => {
    try {
      // Kiểm tra key hợp lệ
      if (typeof key !== 'string' || !key) {
        console.warn('Invalid translation key:', key);
        return '';
      }
      
      // Lấy chuỗi dịch hoặc trả về key nếu không tìm thấy
      let text = translations[language]?.[key] || key;
      
      // Thay thế tham số nếu có
      if (params && typeof params === 'object' && Object.keys(params).length > 0) {
        Object.entries(params).forEach(([param, value]) => {
          const regex = new RegExp(`\\{${param}\\}`, 'g');
          const strValue = convertValueToString(value, param);
          text = text.replace(regex, strValue);
        });
      }
      
      return text;
    } catch (error) {
      console.error('Translation error:', error);
      return typeof key === 'string' ? key : '';
    }
  };
  
  // Hàm hỗ trợ chuyển đổi giá trị thành chuỗi an toàn
  function convertValueToString(value: any, paramName: string): string {
    if (value === undefined || value === null) {
      return '';
    }
    
    if (typeof value === 'object') {
      try {
        return String(value);
      } catch (err) {
        console.warn(`Error converting object param ${paramName}:`, err);
        return '';
      }
    }
    
    try {
      return String(value);
    } catch (err) {
      console.warn(`Error converting param ${paramName}:`, err);
      return '';
    }
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Hook để sử dụng context này
export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}; 